lingui/eslint-plugin

package.json

it was to strict: nodejs 16 only. Loose strictness for everything up 16

chore: change nodejs engine requirement

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

`ignoreFunction` was not properly working as configured

fix: no-unlocalized properly utilize ignoreFunction option

---

tests/src/rules/no-unlocalized-strings.test.ts

test: add a new test case for the ignoreFunction option

---

README.md
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

Adds `ignoreProperty` option to `no-unlocalized-strings` rule as discussed here https://github.com/lingui/eslint-plugin/discussions/17

feat(no-unlocalized-strings): add ignoreProperty option

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

**Changes**:
-   Updated parent nodes for processing `Literal` and `TemplateLiteral` in the context of TypeScript enums. The modifications are as follows:
```diff
-'TSEnumDeclaration > Literal'(node: TSESTree.Literal) {
+'TSEnumMember > Literal'(node: TSESTree.Literal) {
-'TSEnumDeclaration > TemplateLiteral'(node: TSESTree.TemplateLiteral) {
+'TSEnumMember > TemplateLiteral'(node: TSESTree.TemplateLiteral) {
```
**Issue**: The problem was evident when `parserServices.program` was empty, leading to incorrect parent node referencing for `Literal` and `TemplateLiteral` within TypeScript enums, affecting the rule's effectiveness.
**Resolution**: By changing the parent node references from `TSEnumDeclaration` to `TSEnumMember` for both `Literal` and `TemplateLiteral`, this fix ensures the …

fix(no-unlocalized-strings): Correct Parent Node Handling for TS Enums

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

**Changes**:
-   Support added for the following syntax patterns:
- ```javascript
t(i18n)({ message: `Hello ${name}` })
```
- ```javascript
custom.wrapper()({message: "Hello!"})
```
**Problem**: Previously, the `isValidFunctionCall` helper did not fully process function calls involving `callee` with a `MemberExpression` type.
**Solution**: The update ensures that `ignoreFunction` within `CallExpression` is properly utilized.

fix(no-unlocalized-strings): Enhanced `no-unlocalized` Rule for advanced syntax support

---

src/rules/no-single-variables-to-translate.ts
tests/src/rules/no-single-varibles-to-translate.test.ts

feat: respect lazy translation tags in no-single-variables-to-translate

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

Fixing https://github.com/lingui/eslint-plugin/issues/37
i've found this one is more annoying that the rest, because 
```ts
MyComponent.displayName = "MyComponent"
```
Is quite popular pattern in react ecosystem. 
Related https://github.com/lingui/eslint-plugin/issues/50
What was changed: 
- `ignoreProperty` now applies to the `MyComponent.displayName = "MyComponent"`
- `displayName` is ignored by default

fix(no-unlocalized-strings): `ignoreProperty` support MemberExpression assignments

---

src/rules/no-expression-in-message.ts
tests/src/rules/no-expression-in-message.test.ts

Lingui allows to embed the `plural` macro inside the `t` macro, creating a message that includes the plural, similar to [nested plurals](https://lingui.dev/ref/macro#plural). 
For an example consider the following macro call:
```javascript
import { plural, t } from '@lingui/macro';
const message = t`Count: ${plural(count, {
one: '# book',
other: '# books',
})}`;
```
It gets represented in the message catalog as a single message: `Count: {count, plural, one {# book} other {# books}}`.
However the `no-expression-in-message` rule currently forbids this pattern since the expression in the template string is not an identifier. This PR changes that behavior, allowing calls to the `plural` function to occur inside the `t` macro.

feat: allow calls to plural function in no-expression-in-message

---

src/rules/no-expression-in-message.ts
tests/src/rules/no-expression-in-message.test.ts

This extends the support for calling a the `plural` macro in a `t` macro introduced in #48 to also apply to `select` and `selectOrdinal`.

fix(no-expression-in-message): add select and selectOrdinal to exclusion

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

Completely ignore from checking literals in computed member expressions, eq:
Partially fixes: https://github.com/lingui/eslint-plugin/issues/38
Tracking issue #50 
```js
// valid
obj["key with space"] 
obj[`key with space`]
```

fix(no-unlocalized-strings): ignore Literals in computed MemberExpression

---

docs/rules/no-unlocalized-strings.md
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

fixes: https://github.com/lingui/eslint-plugin/issues/38
related: https://github.com/lingui/eslint-plugin/issues/50
Leverage power of Typescript to exclude methods defined on specific types.
The method to exclude defined as a `Type.method`. Where type and method matched by name.
Examples of correct code for the `{ "ignoreMethodsOnTypes": ["Foo.bar"], "useTsTypes": true }` option:
```ts
interface Foo {
get: (key: string) => string
}
const foo: Foo
foo.get('string with a spaces')
```
By default, the following methods ate ignored: `Map.get`, `Map.has`, `Set.has`

feat(no-unlocalized-strings): add ignoreMethodsOnTypes option

---

src/rules/no-unlocalized-strings.ts

merge Literal and TemplateLiteral visitors into one. Inline methods which was extracted to be used in these two visitors.

refactor(no-unlocalized-strings): merge visitors

---

docs/rules/no-expression-in-message.md
docs/rules/no-single-variables-to-translate.md
src/helpers.ts
src/rules/no-expression-in-message.ts
src/rules/no-single-variables-to-translate.ts
tests/src/rules/no-expression-in-message.test.ts
tests/src/rules/no-single-varibles-to-translate.test.ts
tests/src/rules/t-call-in-function.test.ts

closes https://github.com/lingui/eslint-plugin/issues/35
> +1 to `Trans` tags, and also inside `msg` (and by extension, `defineMessage` function calls)
> ```ts
>   const obj = { value: "the value" };
>   const example = msg`Expression to the right ${_obj.value} and to the left.`; // no warning here
> ```

feat: support `msg` and `defineMessage` in various rules

---

src/helpers.ts
src/rules/no-expression-in-message.ts
src/rules/no-single-tag-to-translate.ts
src/rules/no-single-variables-to-translate.ts
src/rules/no-trans-inside-trans.ts
tests/src/rules/no-expression-in-message.test.ts
tests/src/rules/no-single-variables-to-translate.test.ts

Support messages defined as MessageDescriptor `` t({message: `Hello ${user}`}) `` in `no-expression-in-message` and `no-single-variables-to-translate`.

feat: support messages defined as MessageDescriptor

---

docs/rules/text-restrictions.md
src/helpers.ts
src/rules/no-expression-in-message.ts
src/rules/no-single-variables-to-translate.ts
src/rules/no-unlocalized-strings.ts
src/rules/text-restrictions.ts
tests/src/rules/no-expression-in-message.test.ts
tests/src/rules/no-single-variables-to-translate.test.ts
tests/src/rules/text-restrictions.test.ts

text-restriction rule had a very strange setting `isOnlyForTranslation` which was false by default. It applied restriction rules to all string literals not only for those belonging to lingui.
I think this is not a reasonable default, and it might had sense for author's private project, but doesn't have a sense for lingui. 
So this PR removes this settings. Make it only check the lingui messages, and also a complete refactoring of that rule.

feat(text-restrictions): apply rules only for translation messagessupport different lingui signatures

---

src/rules/no-expression-in-message.ts
tests/src/rules/no-expression-in-message.test.ts

closes https://github.com/lingui/eslint-plugin/issues/67
* now `no-expression-in-message` correctly handles text in the `JSXExpressionContainer` in the `<Trans>` component. (e.g `` <Trans>{`How much is ${obj.prop}?`}</Trans> ``) I don't know why someone should do that, but it supported by lingui macro, so the eslint rule just followed a logic. 
* rule now will report every expression in the mesage separately, so for the `` t`hello ${obj.prop} ${obj.prop}?` `` it will report 2 errors, and IDE will highlight each expression separately instead of the whole message. 
* `{' '}` don't triggering an issue nymore, as it fails into first category (text)

feat(no-expression-in-message): correctly handle {' '} in JSX, report for each found expression

---

docs/rules/no-unlocalized-strings.md
src/helpers.ts
src/rules/no-single-variables-to-translate.ts
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

* improved error messages, instead of "disallow literal string" it now will show 
```
"String not marked for translation. Wrap it with t``, <Trans>, or msg``." 
```
* added support for regex patterns for `ignoreAttribute`, `strictAttribute`, `ignoreProperty` options
* refactored code, make it cleaner, removed duplicating logic
* refined documentation for that rule

feat(no-unlocalized-strings): add regex patterns support

---

docs/rules/no-unlocalized-strings.md
src/helpers.ts
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

Preparing the code of the rule to be fully configurable from options. Extract hardcoded pieces and add options to configure them. 
This PR adds `ignoreVariable` options and doesn't bring any breaking changes.

feat(no-unlocalized-strings): add ignoreVariable option + refactor options

---

docs/rules/no-unlocalized-strings.md
package.json
src/helpers.test.ts
src/helpers.ts
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts
yarn.lock

This PRs brings patterns for `ignoreFunction` option. 
Behavior of `ignoreFunction` is changed.  Strings passed to this options are matched using `micromatch` against full callee path (`ctx.myNode.addEventListener`). You need to update your options accordingly. 
Example:
Previously: 
```js
// { "ignoreFunction": ["addEventListener"] }
myNode.addEventListener() //  ✅ match
addEventListener() //  ✅ match
ctx.myNode.addEventListener() // ❌ not match
```
Now:
```js
// { "ignoreFunction": ["*.addEventListener"] }
myNode.addEventListener() //  ✅ match
addEventListener() //  ❌ not match
ctx.myNode.addEventListener() // ✅ match
```
`addEventListener`  (without `*.`) will match only `addEventListener()` 
```js
// { "ignoreFunction": ["addEventListener"] }
addEventListener() //  ✅ match …
```

feat(no-unlocalized-strings): add patterns for ignore functions

---

README.md
docs/rules/no-unlocalized-strings.md
src/helpers.ts
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

Quote myself:
> I went through the issues with this rule and tried to address them all. It seems like we need a big change in how the rule is set up. There’s no way to make it work perfectly for everyone and every project. So, I’ve decided to remove all the built-in settings and made them fully customizable.
> 
> For example, if a user doesn’t want:
> 
> but we noticed that const CAPITAL_LETTERS is always ignored(?).
> 
> they can simply remove the related regex from their options.
This will fix 
- https://github.com/lingui/eslint-plugin/issues/28 (chinese users will be able to set their own regexp)
- const CAPITAL_LETTERS is always ignored
And possible many more issues in the future regarding the defaults. 
What was done: 
1. All hard-coded default are removed in favor of user …

feat(no-unlocalized-strings): remove default configuration

---

docs/rules/no-unlocalized-strings.md
src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

- ignore when there is no text, and only variables
- apply `ignore` option to the JSX Text
- improve default Regexp in the documentation

fix(no-unlocalized-strings): ignore more cases

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

**Description:**
This PR addresses an issue where the `no-unlocalized-strings` ESLint rule incorrectly flags default parameter values as unlocalized strings, even when their parameter names are included in the `ignoreNames` option.
**Background:**
Given the following code and ESLint configuration:
```javascript
// Code
function Input({ intent = "none" }) {}
// ESLint Configuration
{
"rules": {
"no-unlocalized-strings": ["error", { "ignoreNames": ["intent"] }]
}
}
```
The string `"none"` assigned as a default value to `intent` should be ignored, but it is currently being reported as an error.
**Solution:**
Added a handler for `AssignmentPattern` nodes to check if the parameter name is in `ignoreNames`. If it is, the default value is ignored by adding it to the `visited` set.
**Testing:**
- …

fix: no-unlocalized-strings rule to ignore default parameter values specified in ignoreNames

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

**Description:**
This PR fixes an issue in the `no-unlocalized-strings` ESLint rule where string literals assigned to object properties are incorrectly reported as unlocalized strings when using TypeScript's `as const` assertions, even if the property names are specified in the `ignoreNames` option.
**Background:**
When using the `ignoreNames` option with a regex pattern to ignore certain property names, the rule should not report string literals assigned to those properties. However, if the property value includes an `as const` assertion, the rule fails to recognize it due to the `TSAsExpression` node introduced by the TypeScript assertion.
**Example:**
Given the ESLint configuration:
```json
{
"rules": {
"no-unlocalized-strings": [
"error",
{ "ignoreNames": [{ "regex": { "pattern": …
```

fix: no-unlocalized-strings rule to correctly handle as const assertions in property values with ignoreNames

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

**Description:**
This PR addresses an issue in the `no-unlocalized-strings` ESLint rule where string literals within expressions assigned to variables are incorrectly reported as unlocalized strings, even when the variable names are specified in the `ignoreNames` option.
**Background:**
When using the `ignoreNames` option to ignore certain variable names, the rule should not report string literals assigned to those variables. However, if the string literal is part of an expression (e.g., using the nullish coalescing operator `??`, logical OR `||`, or ternary `? :`), the rule currently fails to recognize it and reports an error.
**Example:**
Given the ESLint configuration:
```json
{
"rules": {
"no-unlocalized-strings": [
"error",
{ "ignoreNames": ["variant"] }
]
}
}
```
The following code …

fix: `no-unlocalized-strings` rule to ignore string literals in expressions assigned to variables specified in `ignoreNames`

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

The `no-unlocalized-strings` ESLint rule was incorrectly flagging string literals used in TypeScript type definitions as untranslated strings:
```typescript
interface Props {
"aria-label": string;    // ❌ Was incorrectly flagged
"data-testid": string;   // ❌ Was incorrectly flagged
}
type ButtonVariant = 'primary' | 'secondary';  // ❌ Was incorrectly flagged
```
Modified the rule to properly ignore string literals when they appear in type contexts. All strings in TypeScript type definitions are now correctly ignored as they represent type information rather than actual text content:
```typescript
interface Props {
"aria-label": string;    // ✅ Now correctly ignored
"data-testid": string;   // ✅ Now correctly ignored
}
type ButtonVariant = 'primary' | 'secondary';  // ✅ Now correctly …
```

fix: no-unlocalized-strings corrected support for interface prop names

---

src/rules/no-unlocalized-strings.ts
tests/src/rules/no-unlocalized-strings.test.ts

This PR adds three improvements to the `no-unlocalized-strings` rule:
1. Automatically ignores string literals that are part of `as const` assertions since these are typically used to declare fixed values/constants and are not meant for translation.
Example:
```ts
// This will no longer be flagged
const ROUTES = {
home: "/home" as const,
settings: "/settings" as const
} 
```
2. When `useTsTypes: true` is enabled, ignores string literals that are part of string literal union types, as these usually represent predefined values rather than user-facing strings.
Example:
```ts
type ButtonVariant = "primary" | "secondary";
function Button(props: { variant: ButtonVariant }) { }
// This will no longer be flagged
Button({ variant: "primary" });
```
3. Added support for quoted object keys since …

feat: add support for `as const` assertions, string literal union types, and quoted object keys

---

src/rules/no-expression-in-message.ts
tests/src/rules/no-expression-in-message.test.ts

feat(no-expression-in-message): add support for ph and explicit labels
